#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

void Help() {
    printf("\n##############################################################\n");
    printf("#                    SMOOTH DATA PROGRAM                     #\n");
    printf("#                      AUTHOR: Yujie Liu                     #\n");
    printf("#                        DATE: 2019.04                       #\n");
    printf("##############################################################\n\n");
    printf(">>> DESCRIPTION:\n");
    printf("\tThis program can smooth a series of data points by using moving average methods.\n");
    printf("\tYou should provide input .xvg file (Generated by gmx energy) with Two columns.\n");
    printf("\tThe first column must be \"Time\", the second column is anything.\n");
    printf("===================================================================\n\n\n");
}

int Lines(const char *fn) {
    FILE *fp = NULL;
    char buff[256];
    int i = 0;
    
    if((fp = fopen(fn, "r")) == NULL) {printf("\nError, Not found input file (%s)\n\n", fn); exit(1);}
    while(fgets(buff, sizeof(buff), fp)) {
        if(strstr(buff, "#") == NULL && strstr(buff, "@") == NULL){i++;}
    }
    fclose(fp);
    return i;
}

void ReadXvg(const char *fn, double *data[2]) {
    FILE *fp = NULL;
    char buff[256];
    int i = 0;
    fp = fopen(fn, "r");
    while(fgets(buff, sizeof(buff), fp)) {
        if(strstr(buff, "#") != NULL || strstr(buff, "@") != NULL){continue;}
        else {
            sscanf(buff, "%lf %lf", &data[0][i], &data[1][i]);
            i++;
        }
    }
    fclose(fp);
}



int main(int argc, char *argv[]) {
    if(argc < 2) {
        Help();
        fprintf(stderr, "\nError! No input file\n");
        exit(1);
    }
    Help();
    printf("\t>>Input filename: %s\n\n", argv[1]);
    
    int lines;
    lines = Lines(argv[1]);
    //printf("%d\n", lines);
    
    double *data[2];
    for(int k = 0; k < 2; k++) {
        data[k] = (double *)calloc(lines, sizeof(double));
    }
    
    ReadXvg(argv[1], data);
    //printf("%12.6lf %12.6lf \n", data[0][0], data[1][0]);
    
    int points; //such as 5
    while(1) {
        printf("\tPlease input the length of average [Odd]:\n");
        scanf("%d", &points);
        if(points%2 == 0) {
            printf("\tError! Input number must be odd\n");
        }
        else if(points%2 != 0) { break; }
    }

    printf("\n\t>>You are using %2d points for Running Average...\n", points);
    
    double Ttemp, Tdata, sum;
    int i, j, incr, t;
    FILE *fout = NULL;
    fout = fopen("smooth.dat", "w");
    fprintf(fout, "%12s %12s\n", "#Time (ps)", "Term");
    incr = (points-1)/2;
    for(i = 0; i < lines; i++) {
        sum = 0.0;
        t = 0;
        for(j = i; j <= i+2*incr; j++) {
            if(j >= lines) {
                t = 1;
                break;
            }
            sum += data[1][j];
        }
        if(t == 0) {
            Tdata = sum/points;
            Ttemp = data[0][i+incr];
            fprintf(fout, "%12.6lf %12.6lf\n", Ttemp, Tdata);
        }
    }
    fclose(fout);
    
    for(int k = 0; k < 2; k++) {
        free(data[k]);
    }
    
    printf("\n\t>>File smooth.dat has been generated successfully!!\n");
    
    return 0;
}